// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/hedera/client.go

package mocks

import (
	"reflect"

	"github.com/LimeChain/Hederium/internal/domain"
	"github.com/ethereum/go-ethereum/common"
	"github.com/golang/mock/gomock"
	hedera "github.com/hiero-ledger/hiero-sdk-go/v2/sdk"
)

// MockHederaNodeClient is a mock of HederaNodeClient interface.
type MockHederaNodeClient struct {
	ctrl     *gomock.Controller
	recorder *MockHederaNodeClientMockRecorder
}

// MockHederaNodeClientMockRecorder is the mock recorder for MockHederaNodeClient.
type MockHederaNodeClientMockRecorder struct {
	mock *MockHederaNodeClient
}

// NewMockHederaNodeClient creates a new mock instance.
func NewMockHederaNodeClient(ctrl *gomock.Controller) *MockHederaNodeClient {
	mock := &MockHederaNodeClient{ctrl: ctrl}
	mock.recorder = &MockHederaNodeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHederaNodeClient) EXPECT() *MockHederaNodeClientMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockHederaNodeClient) DeleteFile(fileID *hedera.FileID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockHederaNodeClientMockRecorder) DeleteFile(fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockHederaNodeClient)(nil).DeleteFile), fileID)
}

// GetNetworkFees mocks base method.
func (m *MockHederaNodeClient) GetNetworkFees() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkFees")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkFees indicates an expected call of GetNetworkFees.
func (mr *MockHederaNodeClientMockRecorder) GetNetworkFees() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkFees", reflect.TypeOf((*MockHederaNodeClient)(nil).GetNetworkFees))
}

// SendRawTransaction mocks base method.
func (m *MockHederaNodeClient) SendRawTransaction(transactionData []byte, networkGasPriceInTinyBars int64, callerId *common.Address) (*domain.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRawTransaction", transactionData, networkGasPriceInTinyBars, callerId)
	ret0, _ := ret[0].(*domain.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendRawTransaction indicates an expected call of SendRawTransaction.
func (mr *MockHederaNodeClientMockRecorder) SendRawTransaction(transactionData, networkGasPriceInTinyBars, callerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRawTransaction", reflect.TypeOf((*MockHederaNodeClient)(nil).SendRawTransaction), transactionData, networkGasPriceInTinyBars, callerId)
}

// GetContractByteCode mocks base method.
func (m *MockHederaNodeClient) GetContractByteCode(shard, realm int64, address string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractByteCode", shard, realm, address)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractByteCode indicates an expected call of GetContractByteCode.
func (mr *MockHederaNodeClientMockRecorder) GetContractByteCode(shard, realm, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractByteCode", reflect.TypeOf((*MockHederaNodeClient)(nil).GetContractByteCode), shard, realm, address)
}

// GetOperatorPublicKey mocks base method.
func (m *MockHederaNodeClient) GetOperatorPublicKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorPublicKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetOperatorPublicKey indicates an expected call of GetOperatorPublicKey.
func (mr *MockHederaNodeClientMockRecorder) GetOperatorPublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorPublicKey", reflect.TypeOf((*MockHederaNodeClient)(nil).GetOperatorPublicKey))
}
